# server.name: kibana
# server.host: 0.0.0.0

# Elasticsearch settings
# elasticsearch.hosts: [ "https://elastic-master-01:9200","https://elastic-master-02:9200" ]
# elasticsearch.ssl.certificateAuthorities: [ "${KIBANA_DIR}/config/certificates/ca/ca.crt" ]
# elasticsearch.username: kibana_system
# elasticsearch.password: 9uWS0N8xFj1DR4PMj4PE
# elasticsearch.ssl.verificationMode: certificate

# Elasticsearch monitoring settings
# monitoring.ui.container.elasticsearch.enabled: true

# X-Pack Security
# xpack.security.enabled: true
# xpack.encryptedSavedObjects.encryptionKey: "${XPACK_ENCRYPTION_KEY}"
# xpack.security.encryptionKey: "${XPACK_ENCRYPTION_KEY}"
# xpack.reporting.encryptionKey: "${XPACK_ENCRYPTION_KEY}"

# # SSL settings
# server.ssl.enabled: true
# server.ssl.certificate: "${KIBANA_DIR}/config/certificates/kibana/kibana.crt"
# server.ssl.key: "${KIBANA_DIR}/config/certificates/kibana/kibana.key"
# server.ssl.certificateAuthorities: [ "${KIBANA_DIR}/config/certificates/ca/ca.crt" ]


# fleet settings for Elastic-agent
xpack.fleet.enabled: true
xpack.fleet.agents.enabled: true
# xpack.fleet.agents.tlsCheckDisabled: true
# xpack.fleet.agents.kibana.host: "http://kibana:5601"
# xpack.fleet.agents.elasticsearch.host: "http://elastic-data-node1:9200"

# xpack.ingestManager.enabled: true
# xpack.ingestManager.fleet.enabled: true

